import { AppEvent } from './models/event.model.js';
import { generateId } from './utils.js';

const day = (n: number): Date => new Date(Date.now() + n * 24 * 60 * 60 * 1000);
const past = (n: number): Date => new Date(Date.now() - n * 24 * 60 * 60 * 1000);

export const seedEvents: ReadonlyArray<AppEvent> = [
  {
    id: generateId('evt_meeting'),
    type: 'meeting',
    title: 'Sprint planning',
    description: 'Розписати тікети на наступні два тижні',
    priority: 'high',
    createdAt: past(2),
    startsAt: day(0),
    endsAt: day(0),
    location: 'Zoom · #planning',
    participants: ['Аня', 'Богдан', 'Влад'],
  },
  {
    id: generateId('evt_meeting'),
    type: 'meeting',
    title: '1:1 з тімлідом',
    description: 'Зворотний зв\'язок за квартал',
    priority: 'medium',
    createdAt: past(3),
    startsAt: day(1),
    endsAt: day(1),
    location: 'офіс · мітинг-кімната 3',
    participants: ['Я', 'Тімлід'],
  },
  {
    id: generateId('evt_meeting'),
    type: 'meeting',
    title: 'Демо клієнту',
    description: 'Показати нову сторінку профілю',
    priority: 'critical',
    createdAt: past(1),
    startsAt: day(2),
    endsAt: day(2),
    location: 'Google Meet',
    participants: ['Клієнт', 'PM', 'Я'],
  },
  {
    id: generateId('evt_task'),
    type: 'task',
    title: 'Перевести застосунок на signals',
    description: 'Замінити legacy-сторінки за UI-патерни',
    priority: 'high',
    createdAt: past(5),
    dueDate: day(7),
    status: 'in-progress',
    assignee: 'Я',
  },
  {
    id: generateId('evt_task'),
    type: 'task',
    title: 'Описати release notes',
    description: 'v1.4 — фічі, фікси, breaking changes',
    priority: 'medium',
    createdAt: past(4),
    dueDate: day(3),
    status: 'todo',
    assignee: 'Аня',
  },
  {
    id: generateId('evt_task'),
    type: 'task',
    title: 'Зробити рев\'ю PR #482',
    description: 'CombineLatest + signals у фільтрі',
    priority: 'low',
    createdAt: past(1),
    dueDate: day(1),
    status: 'done',
    assignee: 'Влад',
  },
  {
    id: generateId('evt_reminder'),
    type: 'reminder',
    title: 'Прийняти вітаміни',
    description: 'Магній + Д3 щодня вранці',
    priority: 'low',
    createdAt: past(10),
    remindAt: day(0),
    recurrence: 'daily',
  },
  {
    id: generateId('evt_reminder'),
    type: 'reminder',
    title: 'Подати звіт по витратах',
    description: 'До 5-го числа кожного місяця',
    priority: 'high',
    createdAt: past(3),
    remindAt: day(4),
    recurrence: 'monthly',
  },
  {
    id: generateId('evt_reminder'),
    type: 'reminder',
    title: 'Тренування на терасі',
    description: 'Силова + розтяжка',
    priority: 'medium',
    createdAt: past(7),
    remindAt: day(2),
    recurrence: 'weekly',
  },
];
